### ISSUE TITLE
Custom close button not working

### ISSUE THREAD

**Issue by ritz078** [sniphpet/react-toastify#10]
Even though its rendered, I don't see it being doing anything as there is no click event attached to it [here](https://github.com/sniphpet/react-toastify/blob/master/src/Toast.js#L78)

**Comment by sniphpet** [comment]
Hello,

When using a custom close button, the component will receive a prop ```closeToast```. You need to call it inside your component to close the toast.

```javascript
//The classname toastify__close is used to position the icon on the top right side, you don't need it.
const FontAwesomeCloseButton = ({ closeToast }) => (
  <i
    className="toastify__close fa fa-times"
    onClick={closeToast}
  />
);

...
<ToastContainer autoClose={false} position="top-center" closeButton={<FontAwesomeCloseButton />}/>
...

```

**Comment by ritz078** [comment]
Thanks. Working great.
