### ISSUE TITLE
Feature Request: onHover?

### ISSUE THREAD

**Issue by NullVoxPopuli** [sniphpet/react-toastify#11]
for example: http://stonecircle.github.io/ember-cli-notifications/

there is a timer, visual represented by a progress bar on the bottom, that is paused upon hover (which is super handy if an error toast happens to be long).

Are there plans to have this sort of functionality, or add a hook that would allow us to implement it?

**Comment by sniphpet** [comment]
@NullVoxPopuli I really like this feature ! I'll work on it

**Comment by sniphpet** [comment]
Hello @NullVoxPopuli, just to let you know that the v1.4.0 is live and it includes your feature request.
Have a good day.

**Comment by NullVoxPopuli** [comment]
Thanks a ton! looks great!
![2017-05-07-102357_426x129_scrot](https://cloud.githubusercontent.com/assets/199018/25781979/566e6640-330f-11e7-909d-d841850fd4e2.png)

**Comment by pramodZipGo** [comment]
Can we give some option where the progress should be running though you have hover'd on it. Aftre completion of timeout the toast must disappear

**Comment by fkhadra** [comment]
hey @pramodZipGo,
Yes I will add it to my todo list

**Comment by pramodZipGo** [comment]
Thanks considering my request @fkhadra

**Comment by fkhadra** [comment]
you're welcome !
