### ISSUE TITLE
Turn off pointer events when no toast is displayed

### ISSUE THREAD

**Issue by jcuenod** [sniphpet/react-toastify#12]
I noticed that I'm losing pointer events everything beneath the toastify element. Why not just set `pointer-events: none` while there's no toast being displayed?

**Comment by sniphpet** [comment]
@jcuenod indeed it would be better. I'll release the v1.4.0 tonight or tomorrow. I'll take into account this change. Thanks you

**Comment by sniphpet** [comment]
Hello @jcuenod, just to let you know that the v1.4.0 is live and it takes care of set `pointer-event` when needed.
Have a good day
